Repository ayush-that/FinVeda, pull requests merged in 2024-10, with the labels that each got.

#982 Chatbot Fails to Maintain Conversation Flow (#980)
  about.html
  assets/css/style.css
  assets/js/botpress.js
  blog.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: bug, level3, gssoc24

#968 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, gssoc-ext

#1038 FIXES #997 & #998 (merge conflicts resolved as well)
  Licensing.html
  about.html
  assets/css/Licensing.css
  assets/css/about(inlines).css
  assets/css/blog.css
  assets/css/contributors.css
  assets/css/index.css
  assets/css/login.css
  assets/css/quiz.css
  assets/css/trends.css
  assets/js/Licensing.js
  assets/js/Licensingmodals.js
  assets/js/about.js
  assets/js/blog.js
  assets/js/blogmodals.js
  assets/js/contributors.js
  assets/js/contributorsmodals.js
  assets/js/index.js
  assets/js/indexmodals.js
  assets/js/login.js
  assets/js/quiz.js
  assets/js/quizmodals.js
  assets/js/trends.js
  assets/js/trendsmodals.js
  blog.html
  contributors.html
  index.html
  login.html
  quiz.html
  trends.html
Labels: level3, gssoc-ext, hacktober-accepted

#1054 Register Page is Added
  assets/css/bootstrap.min.css
  assets/css/popup.css
  assets/css/register.css
  index.html
  login.html
Labels: level2, gssoc-ext

#1044 Fixed Eye Icon Alignment in Login and Sign-Up Password Fields
  assets/css/style.css
Labels: level2, gssoc-ext

#1066 [FIX] Nav bar Position, Styling and Hover effect fixed
  assets/css/contributors.css
  assets/css/style.css
  index.html
  navbar.css
Labels: gssoc, gssoc24, gssoc-ext

#1063 Added responsive password strength level meter
  index.html
Labels: gssoc, level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1048 updated footer and add hover effect
  index.html
Labels: gssoc, level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1049 Alignment issue of cards in the user sharing section in home page
  index.html
Labels: good first issue, gssoc, level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1071 Add social media icons to login and sign-up pages
  assets/css/index.css
  index.html
Labels: level2, gssoc-ext

#1075 Create footer.html
  footer.html
Labels: level2, gssoc-ext

#1070 [style]: FAQ Section #969
  faq.html
  index.html
Labels: level2, gssoc-ext

#1073 added a contact form to contact page
  assets/css/card.css
  contact.html
  index.html
  navbar.css
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1078 I had made css changes whenever required
  assets/css/about(inlines).css
  assets/css/about.css
  assets/css/blog.css
  assets/css/login.css
  assets/css/quiz.css
  assets/css/trends.css
  index.html
  navbar.css
Labels: gssoc, level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1102 Update contributing guideline in Readme.md
  README.md
Labels: documentation, gssoc-ext

#1088 Restricted the intro section to home page
  about.html
  blog.html
  careers.html
  quiz.html
  tools/sip.html
  trends.html
Labels: level1, gssoc-ext

#1083 successfully attached the new LOGO of FINVEDA
  assets/css/style.css
  index.html
  logo.png
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1107 Fixed Navbar of about us page #1092
  about.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1109 [Fix] : Carousel button fix
  assets/css/slick.css
  index.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1111 Update README.md
  README.md
Labels: documentation, gssoc-ext

#1101 Fix misaligned navbar layout and improve structure
  about.html
  assets/js/index.js
  careers.html
  contact.html
  index.html
  navbar.css
  tools/sip.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1112 Fixed Navbar of Blog and Careers page #1096
  blog.html
  careers.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1130 Subscribe form enhanced
  assets/css/style.css
Labels: enhancement, level1, gssoc-ext, hacktoberfest-accepted

#1131 Added contact page: Issue no. #1018
  ContactUs.html
  assets/css/ContactUs.css
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1129 issue #999 solved.
  index.html
Labels: gssoc-ext, hacktoberfest-accepted

#1138 Adding social media links in the footer to all the pages
  ContactUs.html
  Licensing.html
  about.html
  blog.html
  careers.html
  contact.html
  contributors.html
  footer.html
  login.html
  quiz.html
  tools/sip.html
  trends.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1136 Fix issue with login and sign-up pages not opening on other pages
  about.html
  assets/css/ContactUs.css
  assets/css/about.css
  assets/css/blog.css
  assets/css/index.css
  assets/css/quiz.css
  assets/css/trends.css
  blog.html
  careers.html
  contact.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1127 ADDED DARK MODE
  index.html
Labels: level2, gssoc-ext, hacktoberfest-accepted

#1162 Fixed misalignment of eye button issue in both Login & Register page ! #1124
  about.html
  assets/css/bootstrap.min.css
  assets/css/style.css
  blog.html
  login.html
Labels: bug, level2, gssoc-ext, hacktoberfest-accepted

#1161 Issue #1132 resolved
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1189 added scroll progress bar
  assets/css/index.css
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1234 Fix: #1196 subscribe button fix
  assets/css/style.css
Labels: bug, level1, gssoc-ext, hacktoberfest-accepted

#1231 Fix #1151 Adding contribution Page
  about.html
  assets/css/about.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1239 Fixed issue #1238 - Update UI of footer in homepage
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1240 fixed issue -#1237 - added back to home button
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1242 Nav bar hover effect enhanced
  assets/css/index.css
  assets/css/style.css
  index.html
  navbar.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1253 Blog cards design enhanced
  assets/css/style.css
Labels: enhancement, level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1261 Update quiz.css
  assets/css/quiz.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1254 Extra name and email section removed #1247
  contact.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1285 Corrected Menu Button Overlaying on text
  index.html
  navbar.css
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1281 added language translator
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1267 Added social media links to the About page
  about.html
Labels: level1, gssoc-ext, hacktoberfest-accepted

#1280 Update footer.html
  footer.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1274 Add Translation Tool done ! #1236
  about.html
  blog.html
  contact.html
  index.html
  quiz.html
  trends.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1286 Inconsistent Behavior of Login and Sign-Up Pages Across Different Pages - Fix
  about.html
  assets/css/about.css
  blog.html
  contact.html
  index.html
  tools/sip.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1287 Issue #1203 solved
  assets/css/style.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1271 Login/Register button color matched with theme fixed issue #1021
  navbar.css
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1293 Fix Progress Bar (Top Scroll Animation) on Home and About Pages
  about.html
  assets/css/index.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1296 Fixed connect with us in footer of about page
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1295 Fix Cursor Trail Effect Not Working on Home Page
  about.html
  assets/js/main.js
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1294 fixed Duplicate Contact us
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1297 Button allinged in center issue #1278
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1321 Blog posts cards color and hovering effects enhanced
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1309 Fix the Title of Contact/your feature
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1312 Update careers title.html
  careers.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1323 solved issue #1302
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1315 Close button not working in FAQ already fixed #1184
  assets/css/about(inlines).css
  assets/css/about.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1316 Fix:#1299 contact information fix
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1310 Title: Authentication in login page #1147
  auth.css
  auth.html
  auth.js
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1313 Fix: #1298 size of the button fix
  tools/sipcalculatorCss.css
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1333 ✨issue #1167 solved✨
  auth.js
  index.html
  loginPage.css
  loginPage.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1332 Feedback form enhanced
  assets/css/style.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1327 Alignment of Feedback form
  assets/css/style.css
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1329 Added search bar for jobs functionality for the issue #1262
  careers.css
  careers.html
  careers.js
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1335 Removed excessive space between icons and related text for contact and career pages
  careers.html
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1355 ABOUT US page footer problem solved#1338
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1341 #1224 footer socials updated
  footer.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1360 Fixed Login button in Quiz Section
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1340 Feature/scroll top
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1351 Replaced icons of twitter on all pages to X
  about.html
  blog.html
  careers.html
  contact.html
  quiz.html
  tools/sip.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1366 Headings UI change fix issue #1356
  assets/css/style.css
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1367 Nav bar style applies in every page
  about.html
  assets/css/style.css
  blog.html
  careers.html
  contact.html
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1373 Extra button removed
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1374 NAVBAR ALIGNMENT AND TITLE'S COLOR CHANGE
  assets/css/style.css
  index.html
  navbar.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1368 Fixed Heading texts in Light mode
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1372 Added Emoji Rating with Labels, Validation, and Form Reset Functionality
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1336 solved #1303
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1318 update in Blog card Background color
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1393 Fixed the Clear button functionality on the EMI calculator
  tools/sip.html
  tools/sipcalculatorJs.js
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1379 Improved Blog Post Title Visibility and Fix Login Button Layout
  assets/css/style.css
  blog.html
  navbar.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1402 Layout Fixed
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1378 Fixed the misalignment issue on the Contact page that was impacting the overall user experience.
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1398 Fixed the login button of quiz page
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1407 Fixed the Cookies Consent
  assets/css/cookiepopup.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1418 fixed navbar of licensing page
  Licensing.html
  blogs/privacy-policy.html
  blogs/refund-policy.html
  blogs/terms-of-service.html
  contributors.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1412 Button color changed
  assets/css/index.css
  assets/css/popup.css
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1413 solved issue #1392
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1427 Fixed issue #1420- fixed Whole About us page with footer
  about.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1444 Enhanced User Experience by Replacing Alert Confirmation with Toast Notifications
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1445 implemented "Accept Necessary Cookies Only" option
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1440 fixed password eye's show and hide feature.
  loginPage.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1446 Removed a design bug and alligned the footer UI
  blogs/Types-of-Stock-Investments-A-Quick-Guide.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1438 Enhanced the current structure and also added some more new sections
  CONTRIBUTING.md
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1447 Subscribe form of about us and carrers fixed
  careers.html
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1462 Fixed the about us page
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1467 Fixed about us and added contributor
  about.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1473 1454 - Inconsistent footer
  ContactUs.html
  blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html
  blogs/Pocketmoney.html
  blogs/Types-of-Stock-Investments-A-Quick-Guide.html
  blogs/economic-trends-and-analysis.html
  blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html
  blogs/how-fintech-is-revolutionizing-small-business-lending.html
  blogs/how-to-10x-your-generational-wealth.html
  blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
  blogs/invest-minimal.html
  blogs/real-estate-economics.html
  blogs/saving-for-future.html
  blogs/senior.html
  blogs/starup.html
  blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1471 Fixed the broken layout and UI of the Contact page for improved user experience.
  about.html
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1478 Fix Home Page Cookies Consent Layout and Content Duplication Issues
  assets/css/cookiepopup.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1425 UI improvement of BLOG Page
  assets/images/blog-img.jpeg
  blog.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1488 Fix: #1480 Add placeholder in feedback form
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1487 fixed tools page
  tools/sip.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1485 [BUG FIX]: Enhanced Color Contrast for Headings on Home Page
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1493 Improve FAQ UI and Enhance Smooth Scrolling Experience
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1492 Fix: #1481 Background color fix
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1429 solved #1337
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1494 Fix: #1482 The submit and quiz button fix
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1497 Fix: #1486 The comment section of feedback form fix
  assets/css/style.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1521 Fixed the preloader issue on the About, Quiz, and Help pages to ensure smooth page loading.
  about.html
  faq.html
  quiz.html
Labels: gssoc, level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1469 Implemented sliding animation for mobile navbar and fixed the hamburger icon click functionality.
  ContactUs.html
  Licensing.html
  blog.html
  blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html
  blogs/Pocketmoney.html
  blogs/Types-of-Stock-Investments-A-Quick-Guide.html
  blogs/economic-trends-and-analysis.html
  blogs/empowering-you-with-economic-knowledge-for-smarter-decisions.html
  blogs/how-fintech-is-revolutionizing-small-business-lending.html
  blogs/how-to-10x-your-generational-wealth.html
  blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
  blogs/invest-minimal.html
  blogs/privacy-policy.html
  blogs/real-estate-economics.html
  blogs/refund-policy.html
  blogs/saving-for-future.html
  blogs/senior.html
  blogs/starup.html
  blogs/terms-of-service.html
  blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
  careers.html
  contact.html
  contributors.html
  index.html
  navbar.js
  quiz.html
  tools/sip.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1527 Resolved Duplicate Hero Section Rendering on the Home Page
  index.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1526 Centered cards
  assets/css/index.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1519 Contributors section enhanced
  assets/css/about.css
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1517 I have fixed it (recommended books section, navbar alignment issue)
  assets/css/style.css
  careers.html
  navbar.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1545 Subscribe button fixed
  assets/css/about.css
  contact.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1539 fix the issue cookiepopup buttons
  assets/css/cookiepopup.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1503 add market time with open and close status
  assets/css/market-time.css
  assets/js/market-time.js
  trends.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1558 Fixed Blog Section in Home page
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1559 Fixed Footer of Homepage
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1560 Fixed navbar of quiz page
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1561 Fix Navbar Alignment and Login Button Overflow Issue
  contact.html
  navbar.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1564 [style]: UI IMPROVEMENT IN HELP PAGE #1554
  assets/images/HELP-IMG.jpg
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1573 Scroll to top button made
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1567 Fix Duplicate Help Button on Navbar for Contact and Career Pages
  about.html
  careers.html
  contact.html
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1556 Added hover effect to top stories section on trends.html page
  assets/css/trends.css
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1577 Add a new contributors page done !
  index.html
  tools/contributor.css
  tools/contributor.html
  tools/contributor.js
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1576 updated the issue #1566 by changing the style of header text
  blogs/Mutual-Funds-101-A-Beginners-Guide-to-Smart-Investing.html
  blogs/Pocketmoney.html
  blogs/Types-of-Stock-Investments-A-Quick-Guide.html
  blogs/how-fintech-is-revolutionizing-small-business-lending.html
  blogs/how-to-10x-your-generational-wealth.html
  blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
  blogs/invest-minimal.html
  blogs/privacy-policy.html
  blogs/real-estate-economics.html
  blogs/refund-policy.html
  blogs/saving-for-future.html
  blogs/senior.html
  blogs/starup.html
  blogs/terms-of-service.html
  blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1574 Add Theme Toggle Button and Fix Navbar Bug
  about.html
  assets/css/about.css
  assets/css/style.css
  blog.html
  careers.html
  contact.html
  index.html
  quiz.html
  tools/sip.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1604 Add Troubleshooting Section to README
  README.md
Labels: level1, gssoc24, gssoc-ext

#1608 Feature/bot visibility
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1632 [Feature] Add Real-Time Search Functionality for FAQs
  faq.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1619 added the nav bar to the trends section
  faq.html
  trends.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1643 Enhance the text-visibility in dark-mode
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1640 link every page logo with home page
  ContactUs.html
  about.html
  blog.html
  careers.html
  contact.html
  faq.html
  quiz.html
  trends.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1639 cursor pointer
  assets/css/faq.css
  faq.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1649 Fixed Whole Tools page
  tools/sip.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1650 Fixed Footer of Help page
  faq.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1656 Fixed the allignment of list (Quiz Links & Resources) in footer of QUIZ PAGE
  quiz.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1663 Animation fixed in home page
  assets/css/index.css
  index.html
Labels: level3, gssoc24, gssoc-ext, hacktoberfest-accepted

#1664 Fixed Text color issue !
  faq.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1662 Footer size has been reduced and copyright has been added.
  assets/css/index.css
  footer.html
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1658 To adding animation effect to social media icons
  about.html
  assets/css/about.css
  assets/css/blog.css
  assets/css/index.css
  assets/css/quiz.css
  assets/css/trends.css
  blog.html
  careers.html
  contact.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1666 Fixed the broken Navbar of home page
  index.html
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1676 Expand the width of calculators for better visibility
  index.html
  tools/sip.html
  tools/sipcalculatorCss.css
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1668 Fixed Whole Footer of Homepage
  index.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1691 Creating security.md file
  security.md
Labels: level1, gssoc24, gssoc-ext, hacktoberfest-accepted

#1685 Fixed Multiple Rendering of FAQ Section on Help Page
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1683 Fixed Alignment of FAQ Page Image and Ensure Full Visibility
  faq.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1680 Refactored Navbar by Introducing Dropdown for Better UI/UX
  about.html
  blog.html
  careers.html
  contact.html
  contributors.html
  faq.html
  index.html
  navbar.css
  quiz.html
  trends.html
Labels: level2, gssoc24, gssoc-ext, hacktoberfest-accepted

#1679 Issue: #1345 fixed Overflowing Blog page divs
  assets/css/style.css
Labels: bug, level2, gssoc24, gssoc-ext, hacktoberfest-accepted
