Repository ayush-that/FinVeda, pull requests merged in 2024-06, with the labels that each got.

#221 Resolved both issues #202 and #203
  assets/css/style.css
  assets/js/quiz.js
  blog.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level2, gssoc24

#316 Registration Modal added
  blog.html
  index.html
  login.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level2, gssoc24

#321 Update quiz.js
  assets/js/quiz.js
Labels: gssoc, level1, gssoc24

#350 changed the go to top button colour
  assets/css/style.css
Labels: enhancement, gssoc, level1

#274 Converted Index.html into Different React/Vite Components
  Finveda/Finveda/.eslintrc.cjs
  Finveda/Finveda/.gitignore
  Finveda/Finveda/README.md
  Finveda/Finveda/index.html
  Finveda/Finveda/package-lock.json
  Finveda/Finveda/package.json
  Finveda/Finveda/public/vite.svg
  Finveda/Finveda/src/App.css
  Finveda/Finveda/src/App.jsx
  Finveda/Finveda/src/assets/react.svg
  Finveda/Finveda/src/components/about.jsx
  Finveda/Finveda/src/components/blog.jsx
  Finveda/Finveda/src/components/facts.jsx
  Finveda/Finveda/src/components/features.jsx
  Finveda/Finveda/src/components/footer.jsx
  Finveda/Finveda/src/components/header.jsx
  Finveda/Finveda/src/components/preloader.jsx
  Finveda/Finveda/src/components/testimonial.jsx
  Finveda/Finveda/src/index.css
  Finveda/Finveda/src/main.jsx
  Finveda/Finveda/vite.config.js
Labels: gssoc, level3

#215 Fixed Arrows in blog posts section
  blog.html
Labels: bug, gssoc, level1

#260 Feat/insurance calculator
  tools/insuranceCalculator.js
  tools/sip.html
Labels: enhancement, gssoc, level2
