Repository ayush-that/FinVeda, pull requests merged in 2024-07, with the labels that each got.

#399 Added new scrollbar with hover effects
  assets/css/style.css
Labels: gssoc, level1, gssoc24

#412 Re-Designed The "Scroll-to-Top" button Matching to "Website Design" Theme
  assets/css/style.css
  index.html
  tools/smoothScroll.js
Labels: bug, gssoc, level1, gssoc24

#408 Title: show and hide button near password input
  assets/css/style.css
  blog.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level2, gssoc24

#424 Title : Hovering and border effects added to Blogs
  assets/css/style.css
  blog.html
Labels: gssoc, level1, gssoc24

#428 Reset newslatter and message under form shown
  index.html
Labels: gssoc, level1, gssoc24

#444 Custom Cursor
  assets/images/ads_click_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg
  index.html
Labels: enhancement, gssoc, level2, gssoc24

#434 Made mail link clickable
  index.html
Labels: enhancement, gssoc, level1, gssoc24

#404 [Feature] Added Savings Goal Calculator. [Issue No. #379]
  package-lock.json
  tools/SavingsGoalCalculator.js
  tools/sip.html
  tools/sipcalculatorCss.css
Labels: enhancement, gssoc, level2, gssoc24

#455 Fixed the right side responsiveness issue of 3 pages.
  assets/css/style.css
Labels: enhancement, gssoc, level1, gssoc24

#438 Terms and conditions checkbox
  login.html
Labels: enhancement, gssoc, level2, gssoc24

#460 A slight change in the footer of the website
  blog.html
Labels: enhancement, gssoc, level2, gssoc24

#464 added form invalidation
  blog.html
  index.html
  login.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level3, gssoc24

#475 Changed background of login button on mouse over
  assets/css/style.css
  index.html
Labels: gssoc, level1

#489 Changed the outlook of insurance calculator.
  tools/sip.html
  tools/sipcalculatorCss.css
Labels: gssoc, level2, gssoc24

#493 Added gap between Arthsathi chat bot button & go-to-top button
  assets/js/arthsathi-style.js
  index.html
Labels: gssoc, level1, gssoc24

#494 Fix overlapping of scroll to top added hover/counter on Investing Experts views/like/comment
  assets/css/style.css
  index.html
Labels: gssoc, level2, gssoc24

#500 Footer links working now
  assets/css/style.css
  blog.html
  index.html
  tools/sip.html
  trends.html
Labels: gssoc, level2, gssoc24

#499 Added GST calculator
  tools/GSTcalc.js
  tools/GSTstyle.css
  tools/sip.html
Labels: gssoc, level3, gssoc24

#502 Contributor page added with responsiveness
  assets/css/contributors.css
  contributors.html
  index.html
Labels: gssoc, level3, gssoc24

#506 Title:- Hovering and border effect
  assets/css/style.css
Labels: gssoc, level1, gssoc24

#505 Added The Feedback Comment Button to The All Pages
  blog.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level1, gssoc24

#507 navbar_mobile_view
  assets/css/style.css
Labels: gssoc, level1, gssoc24

#512 made MFI and EMI calculators on tools page responsive at mobile view.
  tools/sip.html
Labels: gssoc, level3, gssoc24

#516 Quiz Section got Responsive
  assets/css/quiz.css
Labels: gssoc, level3, gssoc24

#515 Add Responsive IncomeTax Calc and Made GST/RTO Sumbit Responsive
  tools/IncomeTax.js
  tools/sip.html
Labels: gssoc, level2, gssoc24

#517 Added Margin for small screen in footer's contact section
  assets/css/style.css
  index.html
Labels: gssoc, level1, gssoc24

#523 Consistent calculate button
  tools/sip.html
  tools/sipcalculatorCss.css
Labels: gssoc, gssoc24

#527 Change the color of button text on hovering
  assets/css/style.css
Labels: gssoc, level2, gssoc24

#531 Added Resource Section Footer Links in Missing Pages Footer
  Licensing.html
  blogs/privacy-policy.html
  blogs/refund-policy.html
  blogs/terms-of-service.html
  tools/sip.html
Labels: gssoc, level2, gssoc24

#534 Added Cursor Trail effect Across all the pages
  blog.html
  blogs/privacy-policy.html
  blogs/refund-policy.html
  blogs/terms-of-service.html
  contributors.html
  index.html
  quiz.html
  tools/sip.html
  tools/sip_PPF_cAL.html
  trends.html
Labels: gssoc, level2, gssoc24

#596 Added Navbar and Footer Links in Some Pages
  Licensing.html
  about.html
  blog.html
  blogs/privacy-policy.html
  blogs/refund-policy.html
  blogs/terms-of-service.html
  index.html
  quiz.html
  tools/sip.html
  trends.html
Labels: gssoc, level2, gssoc24

#607 Added hover color
  assets/css/style.css
Labels: gssoc, level1, gssoc24

#667 Updated Outdated Blogs Posts
  blogs/Pocketmoney.html
  blogs/how-fintech-is-revolutionizing-small-business-lending.html
  blogs/how-to-10x-your-generational-wealth.html
  blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
  blogs/invest-minimal.html
  blogs/senior.html
  blogs/starup.html
  blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
Labels: gssoc, level3, gssoc24

#672 Blog redirection
  assets/css/style.css
  index.html
Labels: gssoc, level1, gssoc24

#677 Added About Us Icon
  Licensing.html
  about.html
  blog.html
  blogs/Pocketmoney.html
  blogs/how-fintech-is-revolutionizing-small-business-lending.html
  blogs/how-to-10x-your-generational-wealth.html
  blogs/how-to-deal-with-unknown-risks-in-life-and-investing.html
  blogs/invest-minimal.html
  blogs/privacy-policy.html
  blogs/refund-policy.html
  blogs/senior.html
  blogs/starup.html
  blogs/terms-of-service.html
  blogs/why-investing-in-stocks-is-better-than-fixed-deposit.html
  contributors.html
  index.html
  login.html
  quiz.html
  trends.html
Labels: gssoc, level1, gssoc24

#765 Fixed Navbar in Mobile view Horizontally
  navbar.css
Labels: gssoc, level1, gssoc24

#771 Fixed chatbot sizing for mobile screen
  assets/js/arthsathi-style.js
  index.html
Labels: gssoc, level2, gssoc24

#766 ✔️Added Diagonal-Hovering Effect to Each Card!
  assets/css/contributors.css
  contributors.html
Labels: gssoc, gssoc24

#796 Fixed Feedback form in mobile view
  assets/css/style.css
  index.html
Labels: gssoc, level2, gssoc24

#800 Fixed About us Page in Mobile view
  assets/css/about.css
Labels: gssoc, level3, gssoc24
